# Generated by Django 6.0.5 on 2026-05-08 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchjob',
            options={'ordering': ['-created_at'], 'verbose_name': '批量任务', 'verbose_name_plural': '批量任务'},
        ),
        migrations.AlterModelOptions(
            name='faqdraft',
            options={'ordering': ['image__sort_order', 'id'], 'verbose_name': '问答草稿', 'verbose_name_plural': '问答草稿'},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '上传图片', 'verbose_name_plural': '上传图片'},
        ),
        migrations.AlterModelOptions(
            name='uploadrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '上传记录', 'verbose_name_plural': '上传记录'},
        ),
        migrations.AlterModelOptions(
            name='webhookconfig',
            options={'verbose_name': 'Webhook 配置', 'verbose_name_plural': 'Webhook 配置'},
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='wechat_image_items',
            field=models.JSONField(blank=True, default=list, verbose_name='企业微信图片返回项'),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='wechat_record_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='企业微信记录字段'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='current_step',
            field=models.CharField(blank=True, max_length=255, verbose_name='当前步骤'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='失败数'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='processed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已处理数'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('generating', '生成中'), ('generated', '已生成'), ('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=32, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='任务标题'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='总数'),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='faq.batchjob', verbose_name='所属任务'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='faq.uploadedimage', verbose_name='对应图片'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='是否人工编辑'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='question',
            field=models.CharField(blank=True, max_length=200, verbose_name='主问题'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='similar_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='相似问题'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='status',
            field=models.CharField(choices=[('pending', '待生成'), ('generated', '已生成'), ('failed', '失败')], default='pending', max_length=32, verbose_name='生成状态'),
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faq.batchjob', verbose_name='所属任务'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='faq_images/%Y/%m/%d/', verbose_name='本地图片'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='answer_text',
            field=models.TextField(verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_records', to='faq.batchjob', verbose_name='所属任务'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_records', to='faq.faqdraft', verbose_name='问答草稿'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='image_cdn_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='图片 CDN 链接'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='ok',
            field=models.BooleanField(default=False, verbose_name='是否成功'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='question',
            field=models.CharField(max_length=200, verbose_name='主问题'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='response_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Webhook 完整响应'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='similar_questions',
            field=models.JSONField(default=list, verbose_name='相似问题'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='wechat_record_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='企业微信记录 ID'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='webhook_url',
            field=models.URLField(verbose_name='Webhook 链接'),
        ),
        migrations.CreateModel(
            name='LlmUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, verbose_name='模型')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='输入 Token')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='输出 Token')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='总 Token')),
                ('usage_detail', models.JSONField(blank=True, default=dict, verbose_name='Token 明细')),
                ('ok', models.BooleanField(default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage_logs', to='faq.batchjob', verbose_name='所属任务')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to='faq.faqdraft', verbose_name='问答草稿')),
            ],
            options={
                'verbose_name': 'AI Token 用量',
                'verbose_name_plural': 'AI Token 用量',
                'ordering': ['-created_at'],
            },
        ),
    ]
