# Generated by Django 6.0.5 on 2026-05-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_batchjob_options_alter_faqdraft_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='source_draft_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='来源草稿 ID'),
        ),
    ]
