# Generated by Django 6.0.5 on 2026-05-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_uploadrecord_source_draft_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqdraft',
            options={'ordering': ['generation_item__sort_order', 'image__sort_order', 'id'], 'verbose_name': '问答草稿', 'verbose_name_plural': '问答草稿'},
        ),
        migrations.AlterField(
            model_name='faqdraft',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='faq.uploadedimage', verbose_name='首张图片'),
        ),
        migrations.CreateModel(
            name='GenerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='生成项名称')),
                ('description', models.TextField(verbose_name='生成项描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_combined', models.BooleanField(default=False, verbose_name='是否合并项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_items', to='faq.batchjob', verbose_name='所属任务')),
                ('images', models.ManyToManyField(related_name='generation_items', to='faq.uploadedimage', verbose_name='关联图片')),
            ],
            options={
                'verbose_name': '生成项',
                'verbose_name_plural': '生成项',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='faqdraft',
            name='generation_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='faq.generationitem', verbose_name='生成项'),
        ),
    ]
