# Generated by Django 6.0.5 on 2026-05-08 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': '员工档案', 'verbose_name_plural': '员工档案'},
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='头像链接'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='external_user_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='外部用户 ID'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='raw_profile',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始资料'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='系统用户'),
        ),
    ]
